export const subjectInfo = [
  {
    subjectName: "Physics",
    subjectCode: "PHY",
    classes: "SS1_SCI,SS2_SCI,SS3_SCI",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    subjectName: "Chemistry",
    subjectCode: "CHEM",
    classes: "SS1_SCI,SS2_SCI,SS3_SCI",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: false,
  },
  {
    subjectName: "Biology",
    subjectCode: "BIO",
    classes: "SS1_SCI,SS2_SCI,SS3_SCI",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    subjectName: "Further Mathematics",
    subjectCode: "FMATH",
    classes: "SS1_SCI,SS2_SCI,SS3_SCI",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    subjectName: "English Language",
    subjectCode: "ENG",
    classes: "JSS1,JSS2,JSS3,SS1_SCI,SS2_SCI,SS3_SCI",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    subjectName: "Civic Education",
    subjectCode: "CVE",
    classes: "SS1_SCI,SS2_SCI,SS3_SCI",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    subjectName: "Economics",
    subjectCode: "ECON",
    classes: "SS1_COM,SS2_COM,SS3_COM",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
];
