export const classInfo = [
  {
    className: "SS2B",
    numberOfStudents: 70,
    teacher:
      "Ella Hoffman, David Herbert, Florence Salazar,Lelia Quinn,Owen Frank",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    className: "JSS2B",
    numberOfStudents: 92,
    teacher: "Joe Schultz, Ada Cannon,Alma Rowe,Warren Stokes",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: false,
  },
  {
    className: "JSS3A",
    numberOfStudents: 57,
    teacher: "Frances Gross, Maggie Rodgers,Myrtle Zimmerman,Rosa Johnson",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    className: "SS2A",
    numberOfStudents: 24,
    teacher: "Patrick Santos, Timothy Ramos,Isabelle Mason,Jonathan Luna",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    className: "SS3B",
    numberOfStudents: 93,
    teacher: "Leah Luna, Callie Potter,Victoria McKinney,Elnora Matthews",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    className: "JSS2A",
    numberOfStudents: 6,
    teacher: "Richard Guzman, Julia Powell,Andrew Simon,May Nash",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
  {
    className: "SS3A",
    numberOfStudents: 20,
    teacher: "Don Schneider, Eddie Myers,Adele Maxwell,Sadie Porter",
    class: "Grade 4",
    studentsOffering: "12",
    statusIsActive: true,
  },
];
